springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
  api-docs:
    path: /api-docs

spring:
  sql:
    init:
      mode: always
  mvc:
    dispatch-options-request: true
  profiles:
    include: heroku
  #    include: secure
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace