springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
  api-docs:
    path: /api-docs

spring:
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  header: Authorization
  secret: 'dG95cHJvamVjdGluc3NhZnljYWxsZWRjYXJyb3RmcmllbmR3aXRoc2Vvbmdob29ua2ltYW5kanVzZW9uZ2hvbmc='


